import type { DashboardKpiKey } from "@repo/shared";
import {
  BadgeDollarSign,
  Coins,
  Eye,
  ExternalLink,
  Fingerprint,
  Gauge,
  Heart,
  Link2,
  MessageCircle,
  MessagesSquare,
  MessageSquare,
  MousePointerClick,
  Percent,
  Pointer,
  Repeat,
  Target,
  TrendingUp,
  UserPlus,
  Users,
  Wallet,
} from "lucide-react";

export const KPI_ICONS: Record<DashboardKpiKey, typeof Wallet> = {
  spend: Wallet,
  impressions: Eye,
  reach: Users,
  frequency: Repeat,
  clicks: MousePointerClick,
  clicksAll: Pointer,
  linkClicks: Link2,
  uniqueClicks: Fingerprint,
  ctr: Percent,
  uniqueCtr: Gauge,
  cpc: Coins,
  cpm: BadgeDollarSign,
  landingPageViews: ExternalLink,
  outboundClicks: TrendingUp,
  outboundCtr: Percent,
  leads: UserPlus,
  messagesStarted: MessageSquare,
  messagesContacts: MessagesSquare,
  results: Target,
  costPerResult: BadgeDollarSign,
  postReactions: Heart,
  postComments: MessageCircle,
};